### ISSUE TITLE
Setting up a Message Shortcut action - Routing error - No route matches [POST] "/slack/interaction"

### ISSUE THREAD

**Issue by IsabelleLePivain** [slack-ruby/slack-ruby-bot-server-events-sample#12]
Hi,

Thank you for designing this library. I would need some help to set up a message shortcut action.

I am trying to use a message shortcut. Its ID on my Slack app settings is _desk_message_shortcut_.
I have informed the Interactive Components Request URL with my ngrok Request URL.

I am storing the code for Slack API in the following repository: myrailsapp/app/lib/slack
I am storing the file for the response to the message shortcut here: myrailsapp/app/lib/slack/actions
I basically copied paste the code for the count_letters shortcut, in order to only test the shortcut connection at first:

```
SlackRubyBotServer::Events.configure do |config|
    config.on :action, 'message_action', 'desk_message_shortcut' do |action|
      payload = action[:payload]
      message = payload[:message]
      # action.logger.info "Counting letters in \"#{message[:text]}\"."
      Rails.logger.info("Inside of the shortcut message code")
      # byebug
      { ok: true }
    end
  end  
```
When trying to click the message shortcut from Slack GUI, I get a connection error on Slack end.
In myrailsapp logs, I get the following error message: 

Started POST "/slack/interaction" for .. at 2023-03-14 13:37:58 +0000
Cannot render console from ... Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
**ActionController::RoutingError (No route matches [POST] "/slack/interaction"):**
  
What setting am I missing here?

Thank you,

Isabelle

**Comment by crazyoptimist** [comment]
Could you checkout how routing is handled in [this example](https://github.com/crazyoptimist/slack-rails-bot-starter)?

**Comment by IsabelleLePivain** [comment]
Hi crazyoptimist,

I had been using the wrong Request URL slug.
I replaced my Request URL with BASE_URL/api/slack/action and it works now.

Thank you very much!
